/**
 * Configuration for all 24 Turath hadith collections.
 *
 * Each config defines the book ID, slug, name, and parser settings
 * for extracting hadiths from Turath book pages.
 *
 * Parser types:
 *   - 'standard': N - pattern (most collections)
 *   - 'muslim':   N - (M) dual numbering (Muslim only)
 */

import { join } from "path";

export interface CollectionConfig {
  slug: string;
  bookId: string;
  name: string;
  nameArabic: string;
  source: string;
  cacheDir: string;
  /** Parser type: 'standard' uses N - pattern, 'muslim' uses N - (M) dual numbering */
  parserType: "standard" | "muslim";
  /** Primary isnad/matn delimiter */
  isnadDelimiter: "guillemets" | "double-quotes";
  /** Kitab heading style: standalone = ^كتاب, numbered = ^N - كتاب */
  kitabStyle: "standalone" | "numbered";
  /** Bab heading style */
  babStyle: "standalone" | "numbered" | "none";
  /** Whether collection has chain variants needing letter suffixes */
  hasChainVariants: boolean;
  /** Strip trailing headings from hadith body */
  stripTrailingHeadings: boolean;
  /** Special initial kitab (e.g. Bukhari's بدء الوحي) */
  initialKitab?: { pattern: RegExp; name: string; bab?: string };
  /** Implicit kitab mappings (first hadith number → kitab name) */
  implicitKitabs?: Record<number, string>;
  /** Kitab ranges from existing sunnah.com data — used when text lacks explicit kitab headings */
  kitabRanges?: Array<{ start: number; end: number; name: string }>;
  /** Require N - to be followed by an isnad phrase (أخبرنا/حدثنا) to count as hadith */
  requireIsnadStart?: boolean;
  /** Renumber hadiths sequentially (1, 2, 3...) ignoring per-section numbering in text */
  renumberSequentially?: boolean;
  /** Hadith numbering style: 'standard' = N -, 'dual' = N/ N - (suyuti-style) */
  numberingStyle?: "standard" | "dual";
}

const BASE_DIR = import.meta.dir;

function makeCacheDir(slug: string): string {
  return join(BASE_DIR, `${slug}-pages-cache`);
}

const defaultConfig = {
  source: "turath" as const,
  parserType: "standard" as const,
  isnadDelimiter: "guillemets" as const,
  kitabStyle: "standalone" as const,
  babStyle: "standalone" as const,
  hasChainVariants: false,
  stripTrailingHeadings: false,
};

export const COLLECTIONS: Record<string, CollectionConfig> = {
  // =========================================================================
  // Completed (Bukhari & Muslim) — included for reference/re-processing
  // =========================================================================
  bukhari: {
    ...defaultConfig,
    slug: "bukhari",
    bookId: "1681",
    name: "Sahih al-Bukhari (Sultaniyya)",
    nameArabic: "صحيح البخاري",
    cacheDir: makeCacheDir("bukhari"),
    hasChainVariants: true,
    initialKitab: {
      pattern: /بَدْءُ الْوَحْيِ/,
      name: "بَدْءُ الْوَحْيِ",
      bab: "كَيْفَ كَانَ بَدْءُ الْوَحْيِ إِلَى رَسُولِ اللهِ ﷺ",
    },
  },
  muslim: {
    ...defaultConfig,
    slug: "muslim",
    bookId: "1727",
    name: "Sahih Muslim (Abd al-Baqi)",
    nameArabic: "صحيح مسلم",
    cacheDir: makeCacheDir("muslim"),
    parserType: "muslim",
    isnadDelimiter: "double-quotes",
    kitabStyle: "numbered",
    babStyle: "numbered",
    hasChainVariants: true,
    stripTrailingHeadings: true,
    implicitKitabs: {
      1: "المقدمة",
      8: "كتاب الإيمان",
      223: "كتاب الطهارة",
      293: "كتاب الحيض",
      377: "كتاب الصلاة",
      901: "كتاب الكسوف",
      1079: "كتاب الصيام",
      1171: "كتاب الاعتكاف",
      1471: "كتاب الطلاق",
      2276: "كتاب الفضائل",
    },
  },

  // =========================================================================
  // Phase 1: Kutub al-Sittah
  // =========================================================================
  abudawud: {
    ...defaultConfig,
    slug: "abudawud",
    bookId: "1726",
    name: "Sunan Abu Dawud (Muhyi al-Din 'Abd al-Hamid)",
    nameArabic: "سنن أبي داود",
    cacheDir: makeCacheDir("abudawud"),
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 390, name: "كتاب الطهارة" },
      { start: 391, end: 1160, name: "كتاب الصلاة" },
      { start: 1161, end: 1184, name: "باب تفريع أبواب الوتر" },
      { start: 1185, end: 1192, name: "باب تفريع أبواب قيام الليل" },
      { start: 1193, end: 1213, name: "كتاب شهر رمضان" },
      { start: 1214, end: 1271, name: "باب تفريع أبواب الاستسقاء" },
      { start: 1272, end: 1296, name: "أبواب صلاة السفر" },
      { start: 1297, end: 1313, name: "باب تفريع أبواب التطوع" },
      { start: 1314, end: 1321, name: "باب تفريع أبواب سجود القرآن" },
      { start: 1322, end: 1504, name: "كتاب الزكاة" },
      { start: 1505, end: 1533, name: "كتاب اللقطة" },
      { start: 1534, end: 1543, name: "كتاب قسم الفيء" },
      { start: 1544, end: 1574, name: "كتاب الإمارة" },
      { start: 1575, end: 1891, name: "كتاب الجهاد" },
      { start: 1892, end: 1912, name: "كتاب الأضاحي" },
      { start: 1913, end: 2049, name: "كتاب المناسك" },
      { start: 2050, end: 2187, name: "كتاب النكاح" },
      { start: 2188, end: 2336, name: "كتاب الطلاق" },
      { start: 2337, end: 2381, name: "كتاب الصوم" },
      { start: 2382, end: 2492, name: "كتاب الجنائز" },
      { start: 2493, end: 2494, name: "كتاب الخراج" },
      { start: 2495, end: 2507, name: "باب في ركاز" },
      { start: 2508, end: 2536, name: "باب في الإمارة" },
      { start: 2537, end: 2573, name: "كتاب الأقضية" },
      { start: 2574, end: 2599, name: "كتاب العلم" },
      { start: 2600, end: 2666, name: "كتاب الأشربة" },
      { start: 2667, end: 2739, name: "كتاب الأطعمة" },
      { start: 2740, end: 2757, name: "كتاب الطب" },
      { start: 2758, end: 2832, name: "كتاب العتق" },
      { start: 2833, end: 3594, name: "كتاب البيوع" },
      { start: 3595, end: 3619, name: "كتاب الأيمان والنذور" },
      { start: 3620, end: 3661, name: "كتاب الحدود" },
      { start: 3662, end: 3710, name: "كتاب الديات" },
      { start: 3711, end: 3849, name: "كتاب السنة" },
      { start: 3850, end: 4097, name: "كتاب الجنائز" },
      { start: 4098, end: 4299, name: "كتاب الفتن" },
      { start: 4300, end: 4374, name: "كتاب المهدي" },
      { start: 4375, end: 4466, name: "كتاب الملاحم" },
      { start: 4467, end: 4578, name: "كتاب الحروف والقراءات" },
      { start: 4579, end: 4642, name: "كتاب الحمام" },
      { start: 4643, end: 4743, name: "كتاب اللباس" },
      { start: 4744, end: 4772, name: "كتاب الترجل" },
      { start: 4773, end: 5274, name: "كتاب الأدب" },
    ],
  },
  tirmidhi: {
    ...defaultConfig,
    slug: "tirmidhi",
    bookId: "7895",
    name: "Jami' al-Tirmidhi (Bashar 'Awwad)",
    nameArabic: "جامع الترمذي",
    cacheDir: makeCacheDir("tirmidhi"),
    hasChainVariants: true,
    babStyle: "numbered",
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 148, name: "كتاب الطهارة" },
      { start: 149, end: 451, name: "كتاب الصلاة" },
      { start: 452, end: 487, name: "أبواب الوتر" },
      { start: 488, end: 529, name: "كتاب الجمعة" },
      { start: 530, end: 543, name: "أبواب العيدين" },
      { start: 544, end: 616, name: "أبواب السفر" },
      { start: 617, end: 681, name: "كتاب الزكاة" },
      { start: 682, end: 808, name: "كتاب الصوم" },
      { start: 809, end: 964, name: "كتاب الحج" },
      { start: 965, end: 1079, name: "كتاب الجنائز" },
      { start: 1080, end: 1145, name: "كتاب النكاح" },
      { start: 1146, end: 1174, name: "كتاب الرضاع" },
      { start: 1175, end: 1204, name: "كتاب الطلاق واللعان" },
      { start: 1205, end: 1321, name: "كتاب البيوع" },
      { start: 1322, end: 1385, name: "كتاب الأحكام" },
      { start: 1386, end: 1422, name: "كتاب الديات" },
      { start: 1423, end: 1463, name: "كتاب الحدود" },
      { start: 1464, end: 1492, name: "كتاب الصيد والذبائح" },
      { start: 1493, end: 1523, name: "كتاب الأضاحي" },
      { start: 1524, end: 1547, name: "كتاب النذور والأيمان" },
      { start: 1548, end: 1618, name: "كتاب السير" },
      { start: 1619, end: 1669, name: "كتاب فضائل الجهاد" },
      { start: 1670, end: 1719, name: "كتاب الجهاد" },
      { start: 1720, end: 1787, name: "كتاب اللباس" },
      { start: 1788, end: 1860, name: "كتاب الأطعمة" },
      { start: 1861, end: 1896, name: "كتاب الأشربة" },
      { start: 1897, end: 2035, name: "كتاب البر والصلة" },
      { start: 2036, end: 2089, name: "كتاب الطب" },
      { start: 2090, end: 2115, name: "كتاب الفرائض" },
      { start: 2116, end: 2124, name: "كتاب الوصايا" },
      { start: 2125, end: 2132, name: "كتاب الولاء والهبة" },
      { start: 2133, end: 2157, name: "كتاب القدر" },
      { start: 2158, end: 2269, name: "كتاب الفتن" },
      { start: 2270, end: 2294, name: "كتاب الرؤيا" },
      { start: 2295, end: 2303, name: "كتاب الشهادات" },
      { start: 2304, end: 2414, name: "كتاب الزهد" },
      { start: 2415, end: 2522, name: "كتاب صفة القيامة والرقائق والورع" },
      { start: 2523, end: 2572, name: "كتاب صفة الجنة" },
      { start: 2573, end: 2605, name: "كتاب صفة جهنم" },
      { start: 2606, end: 2644, name: "كتاب الإيمان" },
      { start: 2645, end: 2687, name: "كتاب العلم" },
      { start: 2688, end: 2735, name: "كتاب الاستئذان والآداب" },
      { start: 2736, end: 2858, name: "كتاب الأدب" },
      { start: 2859, end: 2874, name: "كتاب الأمثال" },
      { start: 2875, end: 2926, name: "كتاب ثواب القرآن" },
      { start: 2927, end: 2949, name: "كتاب القراءات" },
      { start: 2950, end: 3369, name: "كتاب تفسير القرآن" },
      { start: 3370, end: 3604, name: "كتاب الدعوات" },
      { start: 3605, end: 3956, name: "كتاب المناقب" },
    ],
  },
  nasai: {
    ...defaultConfig,
    slug: "nasai",
    bookId: "1339",
    name: "Sunan al-Nasai (Abu Ghudda/Risalah)",
    nameArabic: "سنن النسائي",
    cacheDir: makeCacheDir("nasai"),
    isnadDelimiter: "double-quotes",
    hasChainVariants: true,
    requireIsnadStart: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 324, name: "كتاب الطهارة" },
      { start: 325, end: 347, name: "كتاب المياه" },
      { start: 348, end: 395, name: "كتاب الحيض والاستحاضة" },
      { start: 396, end: 447, name: "كتاب الغسل والتيمم" },
      { start: 448, end: 493, name: "كتاب الصلاة" },
      { start: 494, end: 625, name: "كتاب المواقيت" },
      { start: 626, end: 687, name: "كتاب الأذان" },
      { start: 688, end: 741, name: "كتاب المساجد" },
      { start: 742, end: 776, name: "كتاب القبلة" },
      { start: 777, end: 875, name: "كتاب الإمامة" },
      { start: 876, end: 1028, name: "كتاب الافتتاح" },
      { start: 1029, end: 1178, name: "كتاب التطبيق" },
      { start: 1179, end: 1366, name: "كتاب السهو" },
      { start: 1367, end: 1432, name: "كتاب الجمعة" },
      { start: 1433, end: 1458, name: "كتاب تقصير الصلاة في السفر" },
      { start: 1459, end: 1503, name: "كتاب الكسوف" },
      { start: 1504, end: 1528, name: "كتاب الاستسقاء" },
      { start: 1529, end: 1555, name: "كتاب صلاة الخوف" },
      { start: 1556, end: 1597, name: "كتاب صلاة العيدين" },
      { start: 1598, end: 1817, name: "كتاب قيام الليل وتطوع النهار" },
      { start: 1818, end: 2089, name: "كتاب الجنائز" },
      { start: 2090, end: 2434, name: "كتاب الصيام" },
      { start: 2435, end: 2618, name: "كتاب الزكاة" },
      { start: 2619, end: 3084, name: "كتاب مناسك الحج" },
      { start: 3085, end: 3195, name: "كتاب الجهاد" },
      { start: 3196, end: 3388, name: "كتاب النكاح" },
      { start: 3389, end: 3560, name: "كتاب الطلاق" },
      { start: 3561, end: 3593, name: "كتاب الخيل" },
      { start: 3594, end: 3610, name: "كتاب الإحباس" },
      { start: 3611, end: 3671, name: "كتاب الوصايا" },
      { start: 3672, end: 3687, name: "كتاب النحل" },
      { start: 3688, end: 3705, name: "كتاب الهبة" },
      { start: 3706, end: 3719, name: "كتاب الرقبى" },
      { start: 3720, end: 3760, name: "كتاب العمرى" },
      { start: 3761, end: 3938, name: "كتاب الأيمان والنذور" },
      { start: 3939, end: 3965, name: "كتاب عشرة النساء" },
      { start: 3966, end: 4132, name: "كتاب تحريم الدم" },
      { start: 4133, end: 4148, name: "كتاب قسم الفيء" },
      { start: 4149, end: 4211, name: "كتاب البيعة" },
      { start: 4212, end: 4221, name: "كتاب العقيقة" },
      { start: 4222, end: 4262, name: "كتاب الفرع والعتيرة" },
      { start: 4263, end: 4360, name: "كتاب الصيد والذبائح" },
      { start: 4361, end: 4448, name: "كتاب الضحايا" },
      { start: 4449, end: 4705, name: "كتاب البيوع" },
      { start: 4706, end: 4869, name: "كتاب القسامة" },
      { start: 4870, end: 4984, name: "كتاب قطع السارق" },
      { start: 4985, end: 5039, name: "كتاب الإيمان وشرائعه" },
      { start: 5040, end: 5378, name: "كتاب الزينة" },
      { start: 5379, end: 5427, name: "كتاب آداب القضاة" },
      { start: 5428, end: 5539, name: "كتاب الاستعاذة" },
      { start: 5540, end: 5758, name: "كتاب الأشربة" },
    ],
  },
  ibnmajah: {
    ...defaultConfig,
    slug: "ibnmajah",
    bookId: "1198",
    name: "Sunan Ibn Majah (Abd al-Baqi)",
    nameArabic: "سنن ابن ماجه",
    cacheDir: makeCacheDir("ibnmajah"),
    hasChainVariants: true,
    kitabRanges: [
      { start: 1, end: 266, name: "المقدمة" },
      { start: 267, end: 666, name: "كتاب الطهارة وسننها" },
      { start: 667, end: 705, name: "كتاب الصلاة" },
      { start: 706, end: 734, name: "كتاب الأذان والسنة فيها" },
      { start: 735, end: 802, name: "كتاب المساجد والجماعات" },
      { start: 803, end: 1432, name: "كتاب إقامة الصلاة والسنة فيها" },
      { start: 1433, end: 1637, name: "كتاب الجنائز" },
      { start: 1638, end: 1782, name: "كتاب الصيام" },
      { start: 1783, end: 1844, name: "كتاب الزكاة" },
      { start: 1845, end: 2015, name: "كتاب النكاح" },
      { start: 2016, end: 2089, name: "كتاب الطلاق" },
      { start: 2090, end: 2136, name: "كتاب الكفارات" },
      { start: 2137, end: 2307, name: "كتاب التجارات" },
      { start: 2308, end: 2374, name: "كتاب الأحكام" },
      { start: 2375, end: 2389, name: "كتاب الهبات" },
      { start: 2390, end: 2435, name: "كتاب الصدقات" },
      { start: 2436, end: 2491, name: "كتاب الرهون" },
      { start: 2492, end: 2501, name: "كتاب الشفعة" },
      { start: 2502, end: 2511, name: "كتاب اللقطة" },
      { start: 2512, end: 2532, name: "كتاب العتق" },
      { start: 2533, end: 2614, name: "كتاب الحدود" },
      { start: 2615, end: 2694, name: "كتاب الديات" },
      { start: 2695, end: 2718, name: "كتاب الوصايا" },
      { start: 2719, end: 2752, name: "كتاب الفرائض" },
      { start: 2753, end: 2881, name: "كتاب الجهاد" },
      { start: 2882, end: 3119, name: "كتاب المناسك" },
      { start: 3120, end: 3161, name: "كتاب الأضاحي" },
      { start: 3162, end: 3199, name: "كتاب الذبائح" },
      { start: 3200, end: 3250, name: "كتاب الصيد" },
      { start: 3251, end: 3370, name: "كتاب الأطعمة" },
      { start: 3371, end: 3435, name: "كتاب الأشربة" },
      { start: 3436, end: 3549, name: "كتاب الطب" },
      { start: 3550, end: 3656, name: "كتاب اللباس" },
      { start: 3657, end: 3826, name: "كتاب الأدب" },
      { start: 3827, end: 3892, name: "كتاب الدعاء" },
      { start: 3893, end: 3926, name: "كتاب تعبير الرؤيا" },
      { start: 3927, end: 4099, name: "كتاب الفتن" },
      { start: 4100, end: 4341, name: "كتاب الزهد" },
    ],
  },

  // =========================================================================
  // Phase 2: Other sunnah.com collections
  // =========================================================================
  ahmad: {
    ...defaultConfig,
    slug: "ahmad",
    bookId: "25794",
    name: "Musnad Ahmad (Risalah/Arnaut)",
    nameArabic: "مسند أحمد",
    cacheDir: makeCacheDir("ahmad"),
    hasChainVariants: true,
    babStyle: "none",
    kitabRanges: [
      { start: 1, end: 28000, name: "مسند أحمد" },
    ],
  },
  malik: {
    ...defaultConfig,
    slug: "malik",
    bookId: "1699",
    name: "Muwatta Malik (Yahya/Abd al-Baqi)",
    nameArabic: "موطأ مالك",
    cacheDir: makeCacheDir("malik"),
    hasChainVariants: true,
    renumberSequentially: true,
    kitabRanges: [
      { start: 1, end: 2000, name: "موطأ مالك" },
    ],
  },
  darimi: {
    ...defaultConfig,
    slug: "darimi",
    bookId: "21795",
    name: "Sunan al-Darimi (Husayn Asad)",
    nameArabic: "سنن الدارمي",
    cacheDir: makeCacheDir("darimi"),
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 649, name: "مقدمة" },
      { start: 650, end: 1159, name: "كِتَاب الطَّهَارَةِ" },
      { start: 1160, end: 1578, name: "كِتَاب الصَّلَاةِ" },
      { start: 1579, end: 1637, name: "كِتَابِ الزَّكَاةِ" },
      { start: 1638, end: 1735, name: "كِتَابِ الصَّوْمِ" },
      { start: 1736, end: 1888, name: "كِتَابِ الْمَنَاسِكِ" },
      { start: 1889, end: 1943, name: "كِتَابِ الْأَضَاحِيِّ" },
      { start: 1944, end: 1959, name: "كِتَابِ الصَّيْدِ" },
      { start: 1960, end: 2022, name: "كِتَابِ الْأَطْعِمَةِ" },
      { start: 2023, end: 2071, name: "كِتَابِ الْأَشْرِبَةِ" },
      { start: 2072, end: 2098, name: "كِتَابِ الرُّؤْيَا" },
      { start: 2099, end: 2190, name: "كِتَابِ النِّكَاحِ" },
      { start: 2191, end: 2222, name: "كِتَابِ الطَّلَاقِ" },
      { start: 2223, end: 2255, name: "كِتَابِ الْحُدُودِ" },
      { start: 2256, end: 2273, name: "كِتَابِ النُّذُورِ وَالْأَيْمَانِ" },
      { start: 2274, end: 2311, name: "كِتَابِ الدِّيَاتِ" },
      { start: 2312, end: 2359, name: "كِتَاب الْجِهَادِ" },
      { start: 2360, end: 2450, name: "كِتَابِ السِّيَرِ" },
      { start: 2451, end: 2547, name: "كِتَابِ الْبُيُوعِ" },
      { start: 2548, end: 2622, name: "كِتَابِ الِاسْتِئْذَانِ" },
      { start: 2623, end: 2759, name: "كِتَابِ الرِّقَاقِ" },
      { start: 2760, end: 3084, name: "كِتَابِ الْفَرَائِضِ" },
      { start: 3085, end: 3210, name: "كِتَابِ الْوَصَايَا" },
      { start: 3211, end: 3503, name: "كِتَابِ فَضَائِلِ الْقُرْآنِ" },
    ],
  },
  mishkat: {
    ...defaultConfig,
    slug: "mishkat",
    bookId: "8360",
    name: "Mishkat al-Masabih (Tibrizi)",
    nameArabic: "مشكاة المصابيح",
    cacheDir: makeCacheDir("mishkat"),
    hasChainVariants: true,
    kitabRanges: [
      { start: 1, end: 197, name: "كتاب الإيمان" },
      { start: 198, end: 280, name: "كتاب العلم" },
      { start: 281, end: 563, name: "كتاب الطهارة" },
      { start: 564, end: 1522, name: "كتاب الصلاة" },
      { start: 1523, end: 1771, name: "كتاب الجنائز" },
      { start: 1772, end: 1955, name: "كتاب الزكاة" },
      { start: 1956, end: 2108, name: "كتاب الصوم" },
      { start: 2109, end: 2222, name: "كتاب فضائل القرآن" },
      { start: 2223, end: 2504, name: "كتاب الدعوات" },
      { start: 2505, end: 2758, name: "كتاب المناسك" },
      { start: 2759, end: 3040, name: "كتاب البيوع" },
      { start: 3041, end: 3079, name: "كتاب الفرائض والوصايا" },
      { start: 3080, end: 3381, name: "كتاب النكاح" },
      { start: 3382, end: 3405, name: "كتاب العتق" },
      { start: 3406, end: 3445, name: "كتاب الإيمان والنذور" },
      { start: 3446, end: 3554, name: "كتاب القصاص" },
      { start: 3555, end: 3660, name: "كتاب الحدود" },
      { start: 3661, end: 3786, name: "كتاب الإمارة والقضاء" },
      { start: 3787, end: 4063, name: "كتاب الجهاد" },
      { start: 4064, end: 4158, name: "كتاب الصيد والذبائح" },
      { start: 4159, end: 4303, name: "كتاب الأطعمة" },
      { start: 4304, end: 4472, name: "كتاب اللباس" },
      { start: 4473, end: 4605, name: "كتاب الطب والرقى" },
      { start: 4606, end: 4815, name: "كتاب الرؤيا" },
      { start: 4816, end: 5378, name: "كتاب الأدب" },
      { start: 5379, end: 5520, name: "كتاب الفتن" },
      { start: 5521, end: 5738, name: "كتاب أحوال القيامة وبدء الخلق" },
      { start: 5739, end: 5978, name: "كتاب الفضائل والشمائل" },
      { start: 5979, end: 6600, name: "كتاب المناقب" },
    ],
  },
  bulugh: {
    ...defaultConfig,
    slug: "bulugh",
    bookId: "17757",
    name: "Bulugh al-Maram (Fahl)",
    nameArabic: "بلوغ المرام",
    cacheDir: makeCacheDir("bulugh"),
    hasChainVariants: true,
    kitabStyle: "numbered",
    kitabRanges: [
      { start: 1, end: 1600, name: "بلوغ المرام" },
    ],
  },
  adab: {
    ...defaultConfig,
    slug: "adab",
    bookId: "12991",
    name: "al-Adab al-Mufrad (Abd al-Baqi)",
    nameArabic: "الأدب المفرد",
    cacheDir: makeCacheDir("adab"),
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 46, name: "كتاب الْوَالِدَيْنِ" },
      { start: 47, end: 73, name: "كتاب صِلَةِ الرَّحِمِ" },
      { start: 74, end: 75, name: "كتاب مَوَالِي" },
      { start: 76, end: 83, name: "كتاب عول البنات" },
      { start: 84, end: 100, name: "كتاب رعاية الأولاد" },
      { start: 101, end: 128, name: "كتاب الْجَارِ" },
      { start: 129, end: 142, name: "كتاب الْكَرَمِ وَيَتِيمٌ" },
      { start: 143, end: 155, name: "كتاب موت الأولاد" },
      { start: 156, end: 211, name: "كتاب الملكة" },
      { start: 212, end: 220, name: "كتاب الرعاية" },
      { start: 221, end: 237, name: "كتاب الْمَعْرُوفِ" },
      { start: 238, end: 255, name: "كتاب الِانْبِسَاطِ إِلَى النَّاسِ" },
      { start: 256, end: 259, name: "كتاب الْمَشُورَةِ" },
      { start: 260, end: 308, name: "كتاب حسن الخلق" },
      { start: 309, end: 332, name: "كتاب اللعن" },
      { start: 333, end: 343, name: "كتاب المدح" },
      { start: 344, end: 352, name: "كتاب الزِّيَارَةِ" },
      { start: 353, end: 361, name: "كتاب الأكَابِرِ" },
      { start: 362, end: 371, name: "كتاب الصَّغِيرِ" },
      { start: 372, end: 384, name: "كتاب رَحْمَةِ" },
      { start: 385, end: 396, name: "كتاب ذات البين" },
      { start: 397, end: 414, name: "كتاب الهجر" },
      { start: 415, end: 418, name: "كتاب الإشارة" },
      { start: 419, end: 441, name: "كتاب السِّبَابِ" },
      { start: 442, end: 461, name: "كتاب السَّرَفِ فِي الْبِنَاءِ" },
      { start: 462, end: 482, name: "كتاب الرِّفْقِ" },
      { start: 483, end: 490, name: "كتاب الظُّلْم" },
      { start: 491, end: 537, name: "كتاب عيادة المرضى" },
      { start: 538, end: 603, name: "كتاب التصرف العام" },
      { start: 604, end: 738, name: "كتاب الدعاء" },
      { start: 739, end: 753, name: "كتاب الضيف والنفقة" },
      { start: 754, end: 810, name: "كتاب الأقوال" },
      { start: 811, end: 841, name: "كتاب الأسْمَاءِ" },
      { start: 842, end: 855, name: "كتاب الكُنْيَةِ" },
      { start: 856, end: 874, name: "كتاب الشِّعْرِ" },
      { start: 875, end: 887, name: "كتاب الْكَلامِ" },
      { start: 888, end: 906, name: "كتاب عاقبة الأمور" },
      { start: 907, end: 918, name: "كتاب الطيرة" },
      { start: 919, end: 951, name: "كتاب الْعُطَاسَ والتثاؤب" },
      { start: 952, end: 964, name: "كتاب الحركات" },
      { start: 965, end: 1050, name: "كتاب السَّلامِ" },
      { start: 1051, end: 1100, name: "كتاب الاسْتِئْذَانُ" },
      { start: 1101, end: 1116, name: "كتاب أَهْلِ الْكِتَابِ" },
      { start: 1117, end: 1135, name: "كتاب الرَّسَائِلِ" },
      { start: 1136, end: 1152, name: "كتاب الْمَجَالِسِ" },
      { start: 1153, end: 1174, name: "كتاب تعامل الناس" },
      { start: 1175, end: 1198, name: "كتاب الجلوس والاستلقاء" },
      { start: 1199, end: 1204, name: "كتاب الصباح والمساء" },
      { start: 1205, end: 1231, name: "كتاب النوم والمبيت" },
      { start: 1232, end: 1237, name: "كتاب الْبَهَائِمِ" },
      { start: 1238, end: 1243, name: "كتاب الْقَائِلَةِ" },
      { start: 1244, end: 1258, name: "كتاب الْخِتَانِ" },
      { start: 1259, end: 1281, name: "كتاب القمار ونحوه" },
      { start: 1282, end: 1304, name: "كتاب المعرفة" },
      { start: 1305, end: 1316, name: "كتاب الفضول والجفاء" },
      { start: 1317, end: 1322, name: "كتاب الْغَضَبِ" },
    ],
  },
  riyadussalihin: {
    ...defaultConfig,
    slug: "riyadussalihin",
    bookId: "2348",
    name: "Riyad al-Salihin (Fahl)",
    nameArabic: "رياض الصالحين",
    cacheDir: makeCacheDir("riyadussalihin"),
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 679, name: "المقدمات" },
      { start: 680, end: 726, name: "كتاب الأدب" },
      { start: 727, end: 777, name: "كتاب أدب الطعام" },
      { start: 778, end: 812, name: "كتاب اللباس" },
      { start: 813, end: 843, name: "كتاب آداب النوم" },
      { start: 844, end: 893, name: "كتاب السلام" },
      { start: 894, end: 955, name: "كتاب عيادة المريض وتشييع الميت والصلاة عليه وحضور دفنه" },
      { start: 956, end: 990, name: "كتاب آداب السفر" },
      { start: 991, end: 1267, name: "كتاب الفضائل" },
      { start: 1268, end: 1270, name: "كتاب الاعتكاف" },
      { start: 1271, end: 1284, name: "كتاب الحج" },
      { start: 1285, end: 1375, name: "كتاب الجهاد" },
      { start: 1376, end: 1392, name: "كتاب العلم" },
      { start: 1393, end: 1396, name: "كتاب حمد الله تعالى وشكره" },
      { start: 1397, end: 1407, name: "كتاب الصلاة على رسول الله صلى الله عليه وسلم" },
      { start: 1408, end: 1464, name: "كتاب الأذكار" },
      { start: 1465, end: 1510, name: "كتاب الدعوات" },
      { start: 1511, end: 1807, name: "كتاب الأمور المنهي عنها" },
      { start: 1808, end: 1868, name: "كتاب المنثورات والملح" },
      { start: 1869, end: 1896, name: "كتاب الاستغفار" },
    ],
  },
  shamail: {
    ...defaultConfig,
    slug: "shamail",
    bookId: "13037",
    name: "Shamail al-Muhammadiyyah (Julaymi)",
    nameArabic: "الشمائل المحمدية",
    cacheDir: makeCacheDir("shamail"),
    kitabRanges: [
      { start: 1, end: 15, name: "باب ما جاء في خلق رسول الله صلى الله عليه وسلم" },
      { start: 16, end: 23, name: "باب ما جاء في خاتم النبوة" },
      { start: 24, end: 31, name: "باب ما جاء في شعر رسول الله صلى الله عليه وسلم" },
      { start: 32, end: 36, name: "باب ما جاء في ترجل رسول الله صلى الله عليه وسلم" },
      { start: 37, end: 44, name: "باب ما جاء في شيب رسول الله صلى الله عليه وسلم" },
      { start: 45, end: 49, name: "باب ما جاء في خضاب رسول الله صلى الله عليه وسلم" },
      { start: 50, end: 54, name: "باب ما جاء في كحل رسول الله صلى الله عليه وسلم" },
      { start: 55, end: 71, name: "باب ما جاء في لباس رسول الله صلى الله عليه وسلم" },
      { start: 72, end: 73, name: "باب ما جاء في خف رسول الله صلى الله عليه وسلم" },
      { start: 74, end: 85, name: "باب ما جاء في نعل رسول الله صلى الله عليه وسلم" },
      { start: 86, end: 93, name: "باب ما جاء في ذكر خاتم رسول الله صلى الله عليه وسلم" },
      { start: 94, end: 103, name: "باب ما جاء في تختم رسول الله صلى الله عليه وسلم" },
      { start: 104, end: 107, name: "باب ما جاء في صفة سيف رسول الله صلى الله عليه وسلم" },
      { start: 108, end: 110, name: "باب ما جاء في صفة درع رسول الله صلى الله عليه وسلم" },
      { start: 111, end: 112, name: "باب ما جاء في صفة مغفر رسول الله صلى الله عليه وسلم" },
      { start: 113, end: 117, name: "باب ما جاء في عمامة رسول الله صلى الله عليه وسلم" },
      { start: 118, end: 121, name: "باب ما جاء في صفة إزار رسول الله صلى الله عليه وسلم" },
      { start: 122, end: 124, name: "باب ما جاء في مشية رسول الله صلى الله عليه وسلم" },
      { start: 125, end: 125, name: "باب ما جاء في تقنع رسول الله صلى الله عليه وسلم" },
      { start: 126, end: 128, name: "باب ما جاء في جلسته صلى الله عليه وسلم" },
      { start: 129, end: 133, name: "باب ما جاء في تكأة رسول الله صلى الله عليه وسلم" },
      { start: 134, end: 135, name: "باب ما جاء في اتكاء رسول الله صلى الله عليه وسلم" },
      { start: 136, end: 141, name: "باب ما جاء في أكل رسول الله صلى الله عليه وسلم" },
      { start: 142, end: 149, name: "باب ما جاء في صفة خبز رسول الله صلى الله عليه وسلم" },
      { start: 150, end: 183, name: "باب ما جاء في إدام رسول الله صلى الله عليه وسلم" },
      { start: 184, end: 186, name: "باب ما جاء في صفة وضوء رسول الله صلى الله عليه وسلم عند الطعام" },
      { start: 187, end: 193, name: "باب ما جاء في قول رسول الله صلى الله عليه وسلم قبل الطعام وعند الفراغ منه" },
      { start: 194, end: 195, name: "باب ما جاء في قدح رسول الله صلى الله عليه وسلم" },
      { start: 196, end: 202, name: "باب ما جاء في صفة فاكهة رسول الله صلى الله عليه وسلم" },
      { start: 203, end: 204, name: "باب ما جاء في صفة شراب رسول الله صلى الله عليه وسلم" },
      { start: 205, end: 214, name: "باب ما جاء في شرب رسول الله صلى الله عليه وسلم" },
      { start: 215, end: 221, name: "باب ما جاء في تعطر رسول الله صلى الله عليه وسلم" },
      { start: 222, end: 224, name: "باب كيف كان كلام رسول الله صلى الله عليه وسلم" },
      { start: 225, end: 233, name: "باب ما جاء في ضحك رسول الله صلى الله عليه وسلم" },
      { start: 234, end: 239, name: "باب ما جاء في صفة مزاح رسول الله صلى الله عليه وسلم" },
      { start: 240, end: 249, name: "باب ما جاء في صفة كلام رسول الله صلى الله عليه وسلم في الشعر" },
      { start: 250, end: 252, name: "باب ما جاء في كلام رسول الله صلى الله عليه وسلم في السمر" },
      { start: 253, end: 259, name: "باب في صفة نوم رسول الله صلى الله عليه وسلم" },
      { start: 260, end: 286, name: "باب ما جاء في عبادة النبي صلى الله عليه وسلم" },
      { start: 287, end: 295, name: "باب صلاة الضحى" },
      { start: 296, end: 296, name: "باب صلاة التطوع في البيت" },
      { start: 297, end: 312, name: "باب ما جاء في صوم رسول الله صلى الله عليه وسلم" },
      { start: 313, end: 320, name: "باب ما جاء في قراءة رسول الله صلى الله عليه وسلم" },
      { start: 321, end: 326, name: "باب ما جاء في بكاء رسول الله صلى الله عليه وسلم" },
      { start: 327, end: 328, name: "باب ما جاء في فراش رسول الله صلى الله عليه وسلم" },
      { start: 329, end: 341, name: "باب ما جاء في تواضع رسول الله صلى الله عليه وسلم" },
      { start: 342, end: 356, name: "باب ما جاء في خلق رسول الله صلى الله عليه وسلم" },
      { start: 357, end: 358, name: "باب ما جاء في حياء رسول الله صلى الله عليه وسلم" },
      { start: 359, end: 364, name: "باب ما جاء في حجامة رسول الله صلى الله عليه وسلم" },
      { start: 365, end: 369, name: "باب ما جاء في أسماء رسول الله صلى الله عليه وسلم" },
      { start: 370, end: 378, name: "باب ما جاء في عيش رسول الله صلى الله عليه وسلم" },
      { start: 379, end: 384, name: "باب ما جاء في سن رسول الله صلى الله عليه وسلم" },
      { start: 385, end: 399, name: "باب ما جاء في وفاة رسول الله صلى الله عليه وسلم" },
      { start: 400, end: 406, name: "باب ما جاء في ميراث رسول الله صلى الله عليه وسلم" },
      { start: 407, end: 417, name: "باب ما جاء في رؤية رسول الله صلى الله عليه وسلم" },
    ],
  },

  // =========================================================================
  // Phase 3: Small Collections
  // =========================================================================
  nawawi40: {
    ...defaultConfig,
    slug: "nawawi40",
    bookId: "12836",
    name: "al-Arba'in al-Nawawiyyah",
    nameArabic: "الأربعون النووية",
    cacheDir: makeCacheDir("nawawi40"),
    babStyle: "none",
    parserType: "standard" as const, // Uses Phase 3 ordinal parser, not standard
  },
  qudsi40: {
    ...defaultConfig,
    slug: "qudsi40",
    bookId: "19482",
    name: "al-Ahadith al-Qudsiyyah al-Arba'iniyyah",
    nameArabic: "الأحاديث القدسية الأربعينية",
    cacheDir: makeCacheDir("qudsi40"),
    isnadDelimiter: "double-quotes" as const,
    babStyle: "none",
    parserType: "standard" as const, // Uses Phase 3 ordinal parser, not standard
  },
  hisn: {
    ...defaultConfig,
    slug: "hisn",
    bookId: "31307",
    name: "Hisn al-Muslim",
    nameArabic: "حصن المسلم",
    cacheDir: makeCacheDir("hisn"),
    babStyle: "none",
  },

  // =========================================================================
  // Phase 4: HadithUnlocked Large Collections
  // =========================================================================
  "ahmad-zuhd": {
    ...defaultConfig,
    slug: "ahmad-zuhd",
    bookId: "8494",
    name: "al-Zuhd (Ahmad ibn Hanbal)",
    nameArabic: "الزهد لأحمد بن حنبل",
    cacheDir: makeCacheDir("ahmad-zuhd"),
    babStyle: "none",
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 2500, name: "الزهد" },
    ],
  },
  mustadrak: {
    ...defaultConfig,
    slug: "mustadrak",
    bookId: "1424",
    name: "al-Mustadrak (Hakim, Risalah)",
    nameArabic: "المستدرك على الصحيحين",
    cacheDir: makeCacheDir("mustadrak"),
    isnadDelimiter: "double-quotes",
    hasChainVariants: true,
    requireIsnadStart: true,
    stripTrailingHeadings: true,
  },
  "ibn-hibban": {
    ...defaultConfig,
    slug: "ibn-hibban",
    bookId: "537",
    name: "Sahih Ibn Hibban (al-Taqasim wa-l-Anwa')",
    nameArabic: "صحيح ابن حبان",
    cacheDir: makeCacheDir("ibn-hibban"),
    isnadDelimiter: "double-quotes",
    babStyle: "none",
    hasChainVariants: true,
    stripTrailingHeadings: true,
    kitabRanges: [
      { start: 1, end: 7500, name: "صحيح ابن حبان" },
    ],
  },
  "mujam-kabir": {
    ...defaultConfig,
    slug: "mujam-kabir",
    bookId: "1733",
    name: "al-Mu'jam al-Kabir (Tabarani)",
    nameArabic: "المعجم الكبير",
    cacheDir: makeCacheDir("mujam-kabir"),
    hasChainVariants: true,
    babStyle: "none",
    kitabRanges: [
      { start: 1, end: 30000, name: "المعجم الكبير" },
    ],
  },
  "sunan-kubra-bayhaqi": {
    ...defaultConfig,
    slug: "sunan-kubra-bayhaqi",
    bookId: "148486",
    name: "al-Sunan al-Kubra (Bayhaqi, Turki)",
    nameArabic: "السنن الكبرى للبيهقي",
    cacheDir: makeCacheDir("sunan-kubra-bayhaqi"),
    isnadDelimiter: "double-quotes",
    hasChainVariants: true,
    stripTrailingHeadings: true,
  },
  "sunan-kubra-nasai": {
    ...defaultConfig,
    slug: "sunan-kubra-nasai",
    bookId: "8361",
    name: "al-Sunan al-Kubra (Nasai, Risalah)",
    nameArabic: "السنن الكبرى للنسائي",
    cacheDir: makeCacheDir("sunan-kubra-nasai"),
    isnadDelimiter: "double-quotes",
    hasChainVariants: true,
    stripTrailingHeadings: true,
  },
  suyuti: {
    ...defaultConfig,
    slug: "suyuti",
    bookId: "127677",
    name: "Jam' al-Jawami' (Suyuti)",
    nameArabic: "جمع الجوامع (الجامع الكبير)",
    cacheDir: makeCacheDir("suyuti"),
    hasChainVariants: true,
    babStyle: "none",
    isnadDelimiter: "double-quotes",
    numberingStyle: "dual",
    kitabRanges: [
      { start: 1, end: 50000, name: "جمع الجوامع" },
    ],
  },
};

export function getConfig(slug: string): CollectionConfig {
  const config = COLLECTIONS[slug];
  if (!config) {
    console.error(`Unknown collection: ${slug}`);
    console.error(`Available: ${Object.keys(COLLECTIONS).join(", ")}`);
    process.exit(1);
  }
  return config;
}

/** Phase 1: Kutub al-Sittah (remaining) */
export const PHASE_1 = ["abudawud", "tirmidhi", "nasai", "ibnmajah"];

/** Phase 2: Other sunnah.com collections */
export const PHASE_2 = [
  "ahmad", "malik", "darimi", "mishkat", "bulugh",
  "adab", "riyadussalihin", "shamail",
];

/** Phase 3: Small collections */
export const PHASE_3 = ["nawawi40", "qudsi40", "hisn"];

/** Phase 4: HadithUnlocked large collections */
export const PHASE_4 = [
  "ahmad-zuhd", "mustadrak", "ibn-hibban", "mujam-kabir",
  "sunan-kubra-bayhaqi", "sunan-kubra-nasai", "suyuti",
];

/** All remaining collections (excludes bukhari and muslim) */
export const ALL_REMAINING = [...PHASE_1, ...PHASE_2, ...PHASE_3, ...PHASE_4];
